server:
  port: 8011




spring:
  application:
    name: stock-service
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        namespace: public
      server-addr: 127.0.0.1:8848
