server:
  port: 8011
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meet_talk?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Aa1181552548
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: stock-service
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        namespace: public
      server-addr: 127.0.0.1:8848